name: Deploy npm packages to github
on:
    push:
      branches:
        - main
jobs:
  build:
    # environment: build-github-package
    runs-on: ubuntu-latest
    #permissions:
    #    contents: read
    #    packages: write    
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      #- name: Install NodeJS
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 16
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@joergbeicht'       
      - name: Install dependencies
        run: npm ci
      - name: Build Lib
        run: npm run build_and_pack
      #- name: Copy npmrc File
      #  run: cp ./doku/.npmrc ./dist/my-library
      - name: Output contents
        run: ls -la ./dist/my-library        
      - name: publish with Inherited access
        run: npm publish ./dist/my-library
        env:
          NODE_AUTH_TOKEN: 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
      - name: Upload black-duck reports
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: |
            ${{ github.workspace }}/home/runner/.npm/_logs/**/*

      #- name: publish
      #  run: npm publish ./dist/my-library
      #  env:
      #   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Copy npmrc to dist/anylibs
      #  run: echo "copy done"
      #- name: Publish Lib to GitHub Packages
      #  uses: colinparsonscom/publish-node-package@v0.1.0
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }} # optional; must be used with scope
      #    scope: '@joergbeicht' # optional; must be used with github-token